#!/bin/bash

cwd=$(pwd)

get-projects(){
	mkdir ~/Projects
	cd ~/Projects

	input4="$cwd/Data/projects-stuff"
	while IFS= read -r  line
	do
		IFS=', ' read -r -a array <<< "$line"
			git clone git@github.com:${array[0]}/${array[1]}.git
	done < "$input4"
}

get-apt () {
	input1="$cwd/Data/apt-stuff"
	while IFS= read -r  line
	do
		echo "Installing" $line
		echo "------------------------------------------"
		sudo apt-get install $line -y
		echo "Finished installing" $line
		echo "------------------------------------------"
	done <"$input1"

	sudo apt-get update
}

get-snap (){
	input2="$cwd/Data/snap-stuff"
	while IFS= read -r line
	do
		echo "Installing" $line
		echo "------------------------------------------"
		sudo snap install $line
		echo "Finished installing" $line
		echo "------------------------------------------"
	done <"$input2"

	sudo snap refresh
}

get-wallpaper (){
	mkdir ~/Pictures/Wallpapers
	cd ~/Pictures/Wallpapers
	curl -O http://wallpaperget.com/downloadoriginal.php?name=desktop-wallpaper-38.jpg wallpaper.jpg
	gsettings set org.gnome.desktop.background picture-uri 'file:///home/mouzourides/Pictures/wallpaper.jpg'
}

echo "------------------------------------------"
echo "Welcome to the Setup Script!"
echo "------------------------------------------"
echo "Installing your programs"
echo "------------------------------------------"

get-apt
get-snap

echo "------------------------------------------"
echo "Getting your projects"
echo "------------------------------------------"

get-projects

echo "------------------------------------------"
echo "Setting your wallpaper"

get-wallpaper

echo "------------------------------------------"
echo "Done!"
echo "------------------------------------------"
