#!/bin/bash

cwd=$(pwd)

get-projects(){
	echo "Creating Projects directory..."
	mkdir ~/Projects
	cd ~/Projects
	git clone git@github.com:$1/$2.git
}

get-apt () {
	echo "Installing" $1
	sudo apt-get install $1 -y
	echo "Finished installing" $1
echo "------------------------------------------"
}

get-snap (){
	echo "Installing" $1
	sudo snap install $1
	echo "Finished installing" $1
echo "------------------------------------------"
}

echo "------------------------------------------"
echo "Welcome to the Setup Script!"
echo "------------------------------------------"
echo "Installing your programs"
echo "------------------------------------------"

input1="$cwd/apt-stuff"
while IFS= read -r  line
do
        get-apt $line
done <"$input1"

input2="$cwd/snap-stuff"
while IFS= read -r line
do
	get-snap $line
done <"$input2"

sudo apt-get update
sudo snap refresh

echo "------------------------------------------"
echo "Getting your projects"
echo "------------------------------------------"

input4="$cwd/projects-stuff"
while IFS= read -r  line
do
	IFS=', ' read -r -a array <<< "$line"
	get-projects ${array[0]} ${array[1]}
done < "$input4"

echo "------------------------------------------"
echo "Done!"
echo "------------------------------------------"
